name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.1'
          cache: true
      - name: Run GoReleaser
        uses: Justintime50/homebrew-releaser@v1
        with:
          homebrew_owner: kubecolor
          homebrew_tap: homebrew-kubecolor
          formula_folder: Formula
          github_token: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
          update_readme_table: true
          target_darwin_amd64: true
          target_darwin_arm64: true
          target_linux_amd64: true
          target_linux_arm64: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
